services:
  - type: web
    name: premier-auto-sales
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_WEB3FORMS_KEY
        sync: false
      - key: VITE_GEOAPIFY_API_KEY
        sync: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
